Fix link order on Ubuntu 14.04
Specifically, the change fixes this error:
/usr/bin/ld:
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libglut.so:
undefined reference to symbol 'XCreateBitmapFromData'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libX11.so:
error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status